# Generated by Django 4.2.20 on 2026-01-05 14:07

from django.db import migrations

def add_default_sources(apps, schema_editor):
    Source = apps.get_model('finance', 'Source')
    default_sources = [
        'Salary',
        'Freelance',
        'Investment',
        'Gift',
        'Other'
    ]
    for name in default_sources:
        Source.objects.create(name=name, user=None)  # user=None for global/default

def add_default_categories(apps, schema_editor):
    Category = apps.get_model('finance', 'Category')
    default_categories = [
        'Food',
        'Transport',
        'Housing',
        'Utilities',
        'Health',
        'Entertainment',
        'Education',
        'Other'
    ]
    for name in default_categories:
        Category.objects.create(name=name, user=None) # user=None for global/default

class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_source_alter_income_source'),
    ]

    operations = [
        migrations.RunPython(add_default_sources),
        migrations.RunPython(add_default_categories),
    ]
